babyagi.py
Didn't test it, but I assume this works.
That line of code was unreachable before
=> Fixes indentation so sleep is reachable

README.md
The main "babyagi" text which previously was floating on the left is now centered and redirects within the file have been added for users ease of access.
=> Centered Header text and added redirects

babyagi.py
Refactors to use the global index instead of re-defining
=> Refactor index usage in context_agent

.env.example, .gitignore, README.md, argsparser.py, babyagi.py, extensions/argparseext.py, extensions/dotenvext.py
Adding command-line parser, and converting both arg parse and dotenv as extensions. This is just initial suggestion of how we do extensions, likely will have to improve, but it's a good first step top set guidelines for how to add functionality without bloating too much the core app.
=> Command line arguments parser and updates to the dotenv

babyagi.py
Minor refactor to have the vector argument name match the data it holds
=> Refactor vector argument

babyagi.py
If the OpenAI API doesn't answer, the script wait 10 seconds and try again
=> OpenAI API Error managed

.gitignore, babyagi.py
- Removing duplicated `import os` as there doesn't seem to be a reason for it being re-imported
- Adding more spacing between comments, commas, adds, etc.
- Removing unneccessary f-string as there were no variables included in it
- Changing split on `new_tasks` so that it will only split if a \n is found (Doesn't need to split if the there's only one new task without a new line)
=> Formatting, removing unnecessary import, and cleanup for consistency

README.md
=> add some guidelines to the contribution section

babyagi.py
This will make the code more concise and easier to read without affecting the functionality of the program.
=> Remove Double Declaration of Variable

babyagi.py
- Adding a conditional check for splitting to the other split method (meant to add that earlier with the other one, my bad)
=> Adding conditional check to other split method

tools/README.md
Updated the tools README formatting to include code blocks for the Linux commands.
Added `sudo apt update` and auto-confirm install with `-y` flag
=> Update tools README formatting

docs/README-ro.md
Hi, 
This is a translation into the Romanian Language. 
Would be great if you would add it to your repo.
Thank you.
All the best,
D
=> Created README-ro.md file for the Romanian version

README.md, docs/README-zh-tw.md
add Traditional Chinese (zh-TW 🇹🇼) translation to README
=> docs: add Traditional Chinese (zh-TW 🇹🇼) translation to README

README.md, docs/README-es.md
What?
- Include Spanish translation in docs/README-es.md
- Add Spain's flag in the main README.md
Why?
- The spanish community is big in AI, they would definitely benefit from this!
=> Include spanish translation README

Dockerfile, README.md, docker-compose.yml
I found this useful while working with the projcet, so am sharing it here :)
=> Run babyagi inside a docker container

README.md, docs/README-ja.md
I translated and created the Japanese version of the README.
=> Add README-ja.md

inspired-projects.md
@francip not sure how to add this to github pages
=> Update and rename inspired_projects.md to inspired-projects.md

README.md
For new python users, added the run command `python babyagi.py` to the README.md
=> update README to include `python babyagi.py` run command

README.md, docs/README-pl.md
Added polish flag + link in the main README.md and added README-pl.md with translated text.
=> new translation of README.md to Polish language

inspired-projects.md
=> Add PuttyGPT to the list of inspired projects.

README.md, docs/README-hu.md
- Hungarian translation of the README.md is done
- main README.md extended with the Hungarian flag
=> Hungarian translation

inspired-projects.md
I forgot to change the title of my inspired project, so this fixes that
=> Typo in inspired-projects. md

babyagi.py
Context: https://discord.com/channels/1092917289164230770/1093020282891026554/1097968095219433513
If users type in a non-ascii character upsert + query fail type check. E.g. new lines and quotes like these`'`, `"` are all okay. Angled quotes (`“`) and a variety of other special characters are not.
```python
> print(re.sub(ASCII_ONLY, '', 'Hello World 🥰 “"'))
Hello World  "
```
=> Create pinecone compatible key for objective

README.md
i threw the codebase into GPT4 and it gave me this result:
([here](https://dreampuf.github.io/GraphvizOnline/#digraph%20G%20%7B%0A%20%20%20%20graph%20%5Bfontname%20%3D%20%22arial%22%2C%20fontsize%20%3D%2010%5D%3B%0A%20%20%20%20node%20%5Bshape%20%3D%20box%2C%20style%20%3D%20%22filled%22%2C%20fontname%20%3D%20%22arial%22%2C%20fontsize%20%3D%2010%5D%3B%0A%20%20%20%20%0A%20%20%20%20step1%20%5Blabel%20%3D%20%22Step%201%3A%20Pull%20the%20first%20incomplete%20task%22%5D%3B%0A%20%20%20%20execution_agent_node%20%5Blabel%20%3D%20%22Execution%20Agent%22%5D%3B%0A%0A%20%20%20%20step2%20%5Blabel%20%3D%20%22Step%202%3A%20Enrich%20result%20and%20store%20in%20Pinecone%22%5D%3B%0A%20%20%20%20context_agent_node%20%5Blabel%20%3D%20%22Context%20Agent%22%5D%3B%0A%0A%20%20%20%20step3%20%5Blabel%20%3D%20%22Step%2 …
=> add graph of codebase to README.md

babyagi.py
Containing the main loop in a main method makes the code more modular and functional in the long term. Also, it's better to practice keeping that logic in a main function if anyone ever wants to turn this code into a module.
=> Adding main method to contain main loop

classic/ABOUT.md, classic/README.md, classic/babyagi.py, classic/requirements.txt
Adding a folder with the original BabyAGI as a reference or a starting point for folks who don't need the mainline improvements.
=> Adding BabyAGI Classic - the OG Baby

.gitignore, node/.env.example, node/README.md, node/babyagi.js, node/package-lock.json, node/package.json
This PR provides an implementation for the core functionality of BabyAGI in Node.js. It also replaces Pinecone with Chroma based on #186.
Node BabyAGI is contained with the node subdirectory.
=> Implement BabyAGI in Node.js (with Chroma)

.gitattributes
fix for the issue: https://github.com/yoheinakajima/babyagi/issues/181
=> add unix line ending in git attributes

babyagi.py, extensions/pinecone_storage.py, requirements.txt
This fixes Llama embedding usage with the new results store implementations
=> Fixing Llama usage

babyagi.py, extensions/human_mode.py
Human Input.
Ctrl C + Ctrl V
Supports multi line pasting.
=> new mode: human input, as plugin

README.md
Remove reference to Pinecone API since it is no longer necessary.
=> Remove Reference To Pinecone API

README.md, docs/README-de.md
adds docs in German language, including a link from the main page README
=> Add German translation

babyagi.py
=> minor spelling fixes

.env.example, babyagi.py
On my Macbook M1 I had to change the number of threads to 8.
=> Allow changing number of threads for llama.cpp

babyagi.py
https://docs.trychroma.com/telemetry
Perhaps it's better as a CLI --switch?
=> Remove chromadb telemetry.

babyagi.py
Implementation of the fix by @DYSIM for [Issue #223](https://github.com/yoheinakajima/babyagi/issues/233). This seems to get a llama + chroma setup working past the original error for me.
=> Fix for Issue #233 (llama + chroma)

docker-compose.yml, requirements.txt
=> Open up memory limits and add llama_cpp requirement

babyagi.py
Extensive string parsing and prompt engineering changes to improve operation with llama LLMs. Included some new lines that can be uncommented for debugging. Changed `max_tokens` to 2000 for `openai_call` instances. Added escape mechanism from main loop.
=> Further Llama Compatibility

babyagi.py
`Goal configuation` -> `Goal configuration`. Closes #268
=> Fixing a typo in README

docs/inspired-projects.md
AgentLLM is the first PoC for the use of browser-native LLMs in autonomous agents
=> Add AgentLLM to inspired projects

classic/BabyBeeAGI
`autoatically` —> `automatically`
=> Fixing small typo in BabyBeeAGI

README.md
Hello! I noticed that the flag icons that refer to different translations of the README look small. Therefore, to improve readability, I changed the `width` of all icons to 30 instead of 22.
=> Updated translations in README.md

.env.example, README.md, babyagi.py, docs/weaviate.md, extensions/requirements.txt, extensions/weaviate_storage.py
=> Add support for weaviate

docs/README-tr.md
code snippets should not be translated.
=> Turkish translation fix

README.md
Hi Folks,
The instructions on how to get it set up with Weaviate were a bit confusing, I've improved them here!
Thanks
=> README weaviate instructions

requirements.txt
Fixes `error loading model: unrecognized tensor type 7` to support newer local ggml models
=> Bump llama-cpp-python

docs/inspired-projects.md
Hi!  
Adding our project Twitter-Agent🐣  to the inspired projects lists.  Thanks for the awesome work!
You can read more about the project on our [Github Repo](https://github.com/bigsky77/twitter-agent) and you can follow the first iteration of the agent on Twitter!  [lil_bigsky_agi](https://twitter.com/lil_bigsky_agi).
=> Add twitter-agent🐣 to inspired projects lists

README.md, docs/README-vn.md
- Added the Vietnamese version of README.
- Added the shortcut to this version in the main README
=> Added the Vietnamese version of README.
